baseURL = 'https://JustKeepShipping.github.io/my-site/'
languageCode = 'en-us'
title = 'Code Camp'
theme = "PaperMod"
[params]
defaultTheme = "auto" #dark/light based on system
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
    Title = "Coding Camp"
    Content = "Learning coding, networking, infrastructure & cloud — one weekend project at a time."

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
